name: BackstopJS Visual Regression Tests

on:
  push:
  workflow_dispatch:

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        npm install
        npm install -g backstopjs

    - name: Run BackstopJS tests
      run: |
        backstop init
        backstop test

    - name: Archive visual reports
      uses: actions/upload-artifact@v3
      with:
        name: backstopjs-reports
        path: backstop_data/html_report/  # This path might need to be adjusted based on your BackstopJS config
